# Generated by Django 2.2.12 on 2020-05-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0003_photo_is_analyzed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_analyzed',
        ),
    ]
