# Generated by Django 2.2.12 on 2020-05-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0004_remove_photo_is_analyzed'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_analyzed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
