# Generated by Django 2.2.12 on 2020-05-04 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0005_photo_is_analyzed'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoembedding',
            name='user',
            field=models.ForeignKey(db_column='uid', default=1, on_delete=django.db.models.deletion.CASCADE, to='facePhoto.User'),
            preserve_default=False,
        ),
    ]
