# Generated by Django 2.2.12 on 2020-05-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0006_photoembedding_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAlbum',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='facePhoto.User')),
            ],
            options={
                'db_table': 'face_album',
            },
        ),
    ]
