# Generated by Django 2.2.12 on 2020-05-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0009_auto_20200505_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoembedding',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
