# Generated by Django 2.2.12 on 2020-05-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0010_auto_20200505_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoembedding',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
