# Generated by Django 2.2.12 on 2020-05-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0011_auto_20200505_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAlbumNameNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
                ('user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='facePhoto.User')),
            ],
        ),
    ]
