# Generated by Django 2.2.12 on 2020-05-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0012_facealbumnamenumber'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facealbumnamenumber',
            table='face_album_name_number',
        ),
    ]
