# Generated by Django 2.2.12 on 2020-05-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0013_auto_20200505_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_analyzed',
            field=models.IntegerField(default=0),
        ),
    ]
