# Generated by Django 2.2.12 on 2020-05-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0016_photohash'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityPhotoAlbum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'similarity_photo_album',
            },
        ),
        migrations.AlterField(
            model_name='photohash',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SimilarityPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='facePhoto.Photo')),
                ('sp_album', models.ForeignKey(db_column='sp_album_id', on_delete=django.db.models.deletion.CASCADE, to='facePhoto.SimilarityPhotoAlbum')),
            ],
            options={
                'db_table': 'similarity_photo',
            },
        ),
    ]
