# Generated by Django 2.2.12 on 2020-05-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0017_auto_20200513_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarityphoto',
            name='user',
            field=models.ForeignKey(db_column='uid', default=1, on_delete=django.db.models.deletion.CASCADE, to='facePhoto.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='similarityphotoalbum',
            name='user',
            field=models.ForeignKey(db_column='uid', default=1, on_delete=django.db.models.deletion.CASCADE, to='facePhoto.User'),
            preserve_default=False,
        ),
    ]
