# Generated by Django 2.2.12 on 2020-05-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0019_photohash_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photohash',
            name='hash',
            field=models.BigIntegerField(),
        ),
    ]
