# Generated by Django 2.2.12 on 2020-05-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0020_auto_20200513_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photohash',
            name='hash',
            field=models.BigIntegerField(verbose_name=30),
        ),
    ]
