# Generated by Django 2.2.12 on 2020-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0022_auto_20200513_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photohash',
            name='hash',
            field=models.BigIntegerField(),
        ),
    ]
