# Generated by Django 2.2.12 on 2020-05-13 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facePhoto', '0023_auto_20200513_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlurredPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='facePhoto.Photo')),
                ('user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='facePhoto.User')),
            ],
            options={
                'db_table': 'blurred_photo',
            },
        ),
    ]
